### ISSUE TITLE
Failed to parse GPX

### ISSUE THREAD

**Issue by lorenz-py** [progweb/gpx2video#2]
Hi, I'm using the last version of your program but when a GoPro video is imported the program can't decode some of the data streams, therefore the final video with gauges is not created. 
I used the command I found in the readme  to render the video stream with telemetry data.
`./gpx2video -m myvideo.MP4 -g myactivity.gpx -l layout.xml -o output.mp4 --map-source=1 --map-zoom=11 --map-factor 2.0`

```
gpx2video v0.0.0
creation_time = 2022-01-01T15:13:30.000000Z
Failed to find decoder for stream #2
Failed to find decoder for stream #3
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'GX010017.MP4':
  Metadata:
    major_brand     : mp41
    minor_version   : 538120216
    compatible_brands: mp41
    creation_time   : 2022-01-01T15:13:30.000000Z
    firmware        : H21.01.01.20.00
  Duration: 00:00:33.87, start: 0.000000, bitrate: 45393 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 45128 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 29.97 tbc (default)
    Metadata:
      rotate          : 180
      creation_time   : 2022-01-01T15:13:30.000000Z
      handler_name    : GoPro H.265
      encoder         : GoPro H.265 encoder
      timecode        : 15:12:35:21
    Side data:
      displaymatrix: rotation of -180.00 degrees
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      creation_time   : 2022-01-01T15:13:30.000000Z
      handler_name    : GoPro AAC
      vendor_id       : [0][0][0][0]
      timecode        : 15:12:35:21
  Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
    Metadata:
      creation_time   : 2022-01-01T15:13:30.000000Z
      handler_name    : GoPro TCD
      timecode        : 15:12:35:21
  Stream #0:3(eng): Data: bin_data (gpmd / 0x646D7067), 54 kb/s (default)
    Metadata:
      creation_time   : 2022-01-01T15:13:30.000000Z
      handler_name    : GoPro MET
```
This seems to occur with every video I put.
I'm on Manjaro.

Thank you.

**Comment by progweb** [comment]
Hi,

As you use gpx2video command tool, please check that your input files "myactivity.gpx" & "layout.xml" are readable.

myactivity.gpx is an input file. If you don't have got this file... you can try to use gpx2video to get it:
```
./gpx2video -m GOPR1860.MP4 -o myactivity.gpx -f 2 extract
```

About "layout.xml", you can find a valid sample in the source code.

At last, but not least, gpx2video must find the "assets" directory. That's why, I create a symlink in the readme, then I launch gpx2video tool in the parent directory of "assets".

I have just pushed check & control about input arguments.

About : 
```
Failed to find decoder for stream #2
Failed to find decoder for stream #3
```
it's a ffmpeg error. Indeed, the streams:
- Stream #0:2(eng): Data: none (tmcd / 0x64636D74) (default)
- Stream #0:3(eng): Data: bin_data (gpmd / 0x646D7067), 54 kb/s (default)
can't be parsed by ffmpeg.

Thank's to test & use gpx2video.

**Comment by lorenz-py** [comment]
Thank you for your reply. 
I did as you said, I created the symlink and used the sample layout, now the problem seems to be when it starts processing  the video:
```
PACKET: 0 - PTS: 0 - TIMESTAMP: 0 ms - TIME: 2022-01-01 14:13:30 - GPS TIME: 2022-01-01 14:13:26.824 - OFFSET: -4
Video stream synchronized with success
Download map from OpenStreetMap I...
  Download tile 1 / 1 [##################################################] DONE
Build map...
Segmentation fault (core dumped)
```

**Comment by progweb** [comment]
Better...

So, I have just pushed a patch to be able to enable debug traces in adding '-v' flag:

```
./gpx2video -v -m myvideo.MP4 -g myactivity.gpx -l layout.xml -o output.mp4 --map-source=1 --map-zoom=11 --map-factor 2.0
```

Check that the current directory (where is "gpx2video" binary) is writeable. Indeed, for the moment, gpx2video writes a temporary file 'map.png' in the current work path. I have to change it to use "/tmp".

**Comment by lorenz-py** [comment]
The current directory (should be gpx2video/build if I'm right) is writable, in fact  map.png and output.mp4  are created. 

Updated to the last commit, here's the output of the command:

```
PACKET: 0 - PTS: 0 - TIMESTAMP: 0 ms - TIME: 2022-01-01 14:13:30 - GPS TIME: 2022-01-01 14:13:26.824 - OFFSET: -4
Video stream synchronized with success
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:70: called
DEBUG: download:515: called
DEBUG: settings:341: called
Download map from OpenStreetMap I...
DEBUG: download:1011: called
  Download tile 1 / 1 [##################################################] DONE
DEBUG: build:536: called
Build map...
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
Segmentation fault (core dumped)
```

**Comment by progweb** [comment]
If you can run gpx2video with gdb, it could be perfect to help me:

```
$ gdb ./gpx2video
gdb> run -v -m myvideo.MP4 -g myactivity.gpx -l layout.xml -o output.mp4 --map-source=1 --map-zoom=11 --map-factor 2.0
[segfault]
gdb> backtrace
```

Otherwise, is it possible for you to upload a small mp4 from GoPro on Google Drive ?

**Comment by lorenz-py** [comment]
Here's the gdb output:
```
PACKET: 0 - PTS: 0 - TIMESTAMP: 0 ms - TIME: 2022-01-01 14:13:30 - GPS TIME: 2022-01-01 14:13:26.824 - OFFSET: -4
Video stream synchronized with success
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:70: called
DEBUG: download:515: called
DEBUG: settings:341: called
Download map from OpenStreetMap I...
DEBUG: download:1011: called
  Download tile 1 / 1 [##################################################] DONE
DEBUG: build:536: called
Build map...
[New Thread 0x7fff8cb74640 (LWP 8521)]
[New Thread 0x7fff84373640 (LWP 8522)]
[New Thread 0x7fff87fff640 (LWP 8523)]
[New Thread 0x7fff877fe640 (LWP 8524)]
[New Thread 0x7fff86ffd640 (LWP 8525)]
[New Thread 0x7fff867fc640 (LWP 8526)]
[New Thread 0x7fff85ffb640 (LWP 8527)]
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called
DEBUG: run:79: called
DEBUG: perform:159: called
DEBUG: pipehandler:234: called

Thread 1 "gpx2video" received signal SIGSEGV, Segmentation fault.
GPXData::read (this=0x7fffffffdbb0, wpt=0x555556e52a40) at /home/lorenz1/gpx2video/src/gpx.cpp:138
138		for (std::list<gpx::Node*>::const_iterator iter = extensions->getElements().begin();

(gdb) backtrace
#0  GPXData::read(gpx::WPT*) (this=0x7fffffffdbb0, wpt=0x555556e52a40) at /home/lorenz1/gpx2video/src/gpx.cpp:138
#1  0x00005555555747c0 in GPX::retrieveData(long const&) (this=0x555556e4d5a0, timecode=@0x7fffffffdab8: 0)
    at /home/lorenz1/gpx2video/src/gpx.cpp:370
#2  0x000055555558671c in Renderer::run() (this=0x555556e88780) at /home/lorenz1/gpx2video/src/renderer.cpp:314
#3  0x000055555557b3f0 in GPX2Video::run(bool) (done=<optimized out>, this=0x7fffffffdf90)
    at /home/lorenz1/gpx2video/src/gpx2video.h:173
#4  GPX2Video::pipehandler(int, short, void*) (sfd=<optimized out>, kind=<optimized out>, data=0x7fffffffdf90)
    at /home/lorenz1/gpx2video/src/gpx2video.cpp:243
#5  0x00007ffff7f6116e in  () at /usr/lib/libevent-2.1.so.7
#6  0x00007ffff7f61a7f in event_base_loop () at /usr/lib/libevent-2.1.so.7
#7  0x0000555555571e17 in main(int, char**, char**) (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>)
    at /home/lorenz1/gpx2video/src/main.cpp:481
```

**Comment by progweb** [comment]
Great, it's perfect.

Now, it's fixed. GPX extracted from GoPro by gpx2video is very basic and doesn't contain extensions (heartrate, cadence, power...).

**Comment by lorenz-py** [comment]
Thanks! Now it works perfectly. Great project, I will recommend it. Keep it up!

**Comment by progweb** [comment]
Perfect thanks for your time and tests
