### ISSUE TITLE
[BUG] Segfault on video without audio stream

### ISSUE THREAD

**Issue by Zebradil** [progweb/gpx2video#8]
The program fails to process a video from GoPro, which doesn't contain an audio stream. It is a "time-wrap" video and audio is not added there by default.

Not sure about the audio stream, but that's how I understand the gdb output (see below).

**Desktop:**
- OS: Arch Linux (5.17.7-arch1-1, x86_64)
- Version: [`main`](https://github.com/progweb/gpx2video/tree/6d57c73945d4ce2996132170df17d2ea35c957fb) branch

**Additional context**

GDB:
```
(gdb) run --verbose --media ~/archive/tmp/100GOPRO/2022-05-28_ride.mp4 --gpx ~/archive/tmp/100GOPRO/2022-05-28-083827-ELEMNT\ BCA8-120-0.gpx --layout layout.xml --output 2022-05-25_ride_overlay.mp4 video
Starting program: /home/zebradil/development/vendor/gpx2video/build/gpx2video --verbose --media ~/archive/tmp/100GOPRO/2022-05-28_ride.mp4 --gpx ~/archive/tmp/100GOPRO/2022-05-28-083827-ELEMNT\ BCA8-120-0.gpx --layout layout.xml --output 2022-05-25_ride_overlay.mp4 video
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
gpx2video v0.0.0
Failed to find decoder for stream #1
Failed to find decoder for stream #2
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/zebradil/archive/tmp/100GOPRO/2022-05-28_ride.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.16.100
  Duration: 00:12:19.12, start: 0.000000, bitrate: 100434 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 100046 kb/s, 25 fps, 25 tbr, 90k tbn (default)
    Metadata:
      handler_name    : GoPro AVC
      vendor_id       : [0][0][0][0]
      timecode        : 10:39:43:17
    Side data:
      displaymatrix: rotation of -180.00 degrees
  Stream #0:1[0x2](eng): Data: bin_data (gpmd / 0x646D7067), 382 kb/s
    Metadata:
      handler_name    : GoPro MET
  Stream #0:2[0x3](eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : GoPro AVC
      timecode        : 10:39:43:17

Program received signal SIGSEGV, Segmentation fault.
0x000055555558cd17 in AudioParams::AudioParams (this=this@entry=0x7fffffffd180, sample_rate=<error reading variable: Cannot access memory at address 0x50>, channel_layout=<error reading variable: Cannot access memory at address 0x58>, format=<error reading variable: Cannot access memory at address 0x60>) at /home/zebradil/development/vendor/gpx2video/src/audioparams.cpp:14
14              : sample_rate_(sample_rate)
```

Backtrace:
```
#0  0x000055555558cd17 in AudioParams::AudioParams(int const&, unsigned long const&, AudioParams::Format const&)
    (this=this@entry=0x7fffffffd180, sample_rate=<error reading variable: Cannot access memory at address 0x50>, channel_layout=<error reading variable: Cannot access memory at address 0x58>, format=<error reading variable: Cannot access memory at address 0x60>)
    at /home/zebradil/development/vendor/gpx2video/src/audioparams.cpp:14
#1  0x000055555559263d in Renderer::init() (this=0x555556e911f0) at /home/zebradil/development/vendor/gpx2video/src/renderer.cpp:99
#2  0x00005555555949a9 in Renderer::create(GPX2Video&) (app=...) at /home/zebradil/development/vendor/gpx2video/src/renderer.cpp:59
#3  0x000055555557738c in main(int, char**, char**) (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at /home/zebradil/development/vendor/gpx2video/src/main.cpp:524
```

**Comment by progweb** [comment]
Hi,

Thank's for your report... Can you try with the last commit ?

**Comment by Zebradil** [comment]
Wow, that was fast!

Now it proceeds further. Thanks a lot!

**Comment by progweb** [comment]
Great, so you can close issue (or I'll do).

By the way, your video duration is 12min with a high resolution... don't forget that if you interrupt gpx2video rendering (Ctrl + C), the video file will be correctly closed (so you'll be able to read the start of the video result)

**Comment by Zebradil** [comment]
Thanks for the suggestion. It's pretty useful because the entire video processing took 2.5 hours.
